dxw/dfsseta-apply-for-landing-ruby

- .env.example
- .env.test
We are generally "ignoring" .env files as these usually contain secrets -- but there are two which we need to provide:
- `.env.example`: a template for developers to rename, modify
and use locally
- `.env.test`: for automated tests
> Add missing .env files

- .eslintrc.json
- .github/workflows/continuous-integration.yml
- .prettierignore
- .stylelintignore
- Dockerfile
- app/assets/javascripts/cable.js
- app/assets/stylesheets/application.sass.scss
- app/javascript/application.js
- config/application.rb
- config/environments/development.rb
- config/environments/test.rb
- doc/architecture/decisions/0012-standard-terminology.md
- renovate.json
Add a standard CI file to lint, run tests and run brakeman.
Commit some linting fixes.
Ignore the Rollup config in the linter (it does not need linting anyway).
Correct the locations of the build assets in the Stylelint & Prettier ignore files - these files have changed location in Rails 7.
> Add standard CI workflow file

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/pilots_controller.rb
- app/controllers/stages/dates_stage_controller.rb
- app/controllers/stages/destination_stage_controller.rb
- app/controllers/stages_controller.rb
- app/forms/destination_form.rb
- app/views/layouts/application.html.erb
- app/views/pilots/start.html.erb
- app/views/stages/dates_stage/show.html.erb
- app/views/stages/destination_stage/show.html.erb
- config/routes.rb
- spec/features/pilot/stage_0_start_page_understand_service_spec.rb
- spec/features/pilot/stage_1_choose_destination_spec.rb
- spec/forms/destination_form_spec.rb
[Trello ticket 31](https://trello.com/c/LpHfsIFq/31-stage-2-pilot-chooses-destination)
In this PR we:
- propose a pattern for controllers/views for the several stages of the multi-stage questionnaire
- introduce the use of "form objects" to manage validation of each stage independently of any core domain entities which might be handled with the ActiveRecord "model" pattern (e.g. the submission of a final application for a permit)
- implement the first stage of the multi-stage questionnaire: "Pilot chooses destination from list of available landable bodies"
We also:
- introduce the GOV.UK Design System Formbuilder gem from DfE Digital to provide Rails helpers for form elements and error handling
- ~~add the pry-byebug gem to add improve debugging functionality~~ (now in …
> [31] Stage 1: pilot chooses destination

- app/controllers/stages/dates_stage_controller.rb
- app/controllers/stages/registration_number_stage_controller.rb
- app/forms/dates_form.rb
- app/views/stages/dates_stage/show.html.erb
- app/views/stages/registration_number_stage/show.html.erb
- config/routes.rb
- spec/features/pilot/stage_2_supply_landing_and_departure_dates_spec.rb
- spec/forms/dates_form_spec.rb
**This follows on from https://github.com/dxw/dfsseta-apply-for-landing-ruby/pull/27 which needs to be merged first**
Once that "Stage 1" work is merged we'll have 3 commits here:
1. minor tweak to url scheme
2. form object to validate the pair of dates
3. implementation of controller / view and acceptance test
Please see individual commits for detailed commentary.
[Trello card 32](https://trello.com/c/UnyJMgEh/32-stage-2-pilot-provides-landing-and-departure-dates)
- So that my craft can be scheduled in to my destination
- As a pilot
- I want to verify that there is spaceport availability on my preferred landing and departure dates
> (32) Stage 2: Pilot provides landing and departure dates

- script/no-docker/setup
- script/no-docker/update
If you don't already have the compiled assets in `app/assets/builds`, `script/test` will fail and pages will fail to load using `script/server`. This adds the build step to the Docker-less `setup` and `update` scripts, the latter of which is used in the `test` and `server` scripts, to ensure the assets are compiled before they're needed
> Compile assets in setup and update scripts

- Dockerfile
> **Note**
> CI is currently failing on all PRs because of this issue
Currently, our CI is failing on the `Linting CSS` stage with the error `npx: not found`
I'm not really sure why this is, but using the latest version of Node seems to solve the issue.
> Use latest LTS version of Node in Dockerfile

- .eslintrc.json
Our pipeline was failing with an ESLinting error as a result of linting the built JS at `assets/builds/application.js`
```
dfsseta-apply-for-landing-ruby/app/assets/builds/application.js
1:1151   error  't' is defined but never used                                              no-unused-vars
1:1329   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
1:2434   error  'global' is not defined                                                    no-undef
... 
✖ 34 problems (34 errors, 0 warnings)
```
In this commit we tell ESLint to ignore this file.
> Exclude compiled JS from ESLinting in pipeline

- app/controllers/stages/dates_stage_controller.rb
- app/controllers/stages/personal_details_stage_controller.rb
- app/controllers/stages/registration_identifier_stage_controller.rb
- app/controllers/stages/registration_number_stage_controller.rb
- app/forms/spacecraft_registration_identifier_form.rb
- app/views/stages/personal_details_stage/show.html.erb
- app/views/stages/registration_identifier_stage/show.html.erb
- config/routes.rb
- spec/controllers/registration_indentifier_stage_controller_spec.rb
- spec/features/pilot/stage_2_supply_landing_and_departure_dates_spec.rb
- spec/features/pilot/stage_3_supply_registration_identifier_spec.rb
- spec/forms/spacecraft_registration_identifier_form_spec.rb
[Trello 15](https://trello.com/c/BvEYSrto/15-stage-3-supply-spacecraft-registration-identifier)
The registration identifier needs to be in the `XXX111X` format.
See individual commit messages for details.
> [15] Stage 3: Supply registration identifier

- app/controllers/stages/check_your_answers_stage_controller.rb
- app/controllers/stages/personal_details_stage_controller.rb
- app/forms/personal_details_form.rb
- app/views/stages/check_your_answers_stage/show.erb
- app/views/stages/personal_details_stage/show.html.erb
- config/routes.rb
- spec/features/pilot/stage_4_supply_personal_information_spec.rb
- spec/forms/personal_details_form_spec.rb
**NB: [PR 95](https://github.com/dxw/dfsseta-apply-for-landing-ruby/pull/95) Stage 3: Supply registration identifier needs to be merged first**
This PR implements stage 4 of 5 in the "Apply for a Landing" workflow.
See [Trello 18](https://trello.com/c/hMAy7QYS/38-stage-4-supply-personal-details)
The final stage will be "[Check your answers](https://design-system.service.gov.uk/patterns/check-answers/)". The journey then culminates in a "[Success confirmation panel](https://design-system.service.gov.uk/components/panel/)" page.
> [18] Stage 4: supply personal details

- app/views/stages/dates_stage/show.html.erb
- app/views/stages/destination_stage/show.html.erb
- app/views/stages/personal_details_stage/show.html.erb
- app/views/stages/registration_identifier_stage/show.html.erb
[Trello 40](https://trello.com/c/euq784Sd/40-adjust-layout-to-move-heading-below-error-summary): As per https://design-system.service.gov.uk/components/error-summary/#where-to-put-the-error-summary it's more helpful if the error messages come at the top of the form when there are validation error messages to show.
> Move H1 heading below error messages

- app/forms/dates_form.rb
- app/forms/destination_form.rb
- app/forms/spacecraft_registration_identifier_form.rb
- spec/features/pilot/stage_1_choose_destination_spec.rb
- spec/features/pilot/stage_2_supply_landing_and_departure_dates_spec.rb
- spec/features/pilot/stage_3_supply_registration_identifier_spec.rb
- spec/forms/dates_form_spec.rb
- spec/forms/destination_form_spec.rb
- spec/forms/spacecraft_registration_identifier_form_spec.rb
In this PR with improve the validation error messages to conform to the [guidance at: GOV.UK](https://design-system.service.gov.uk/components/text-input/#if-the-input-is-empty).
Stage 4 was fixed up during code review: https://github.com/dxw/dfsseta-apply-for-landing-ruby/pull/98#discussion_r1328778013
> (41) Improve error messages to conform to GOV.UK guidance

- renovate.json
To aid maintenance, we want our renovate config to
auto-merge patches. This is similar to the  [dxw config],
though we use `automergePatch` rather than
`automergeMinor`.
This is a more cautious strategy, more appropriate
for a citizen-facing service.
See [Renovate docs] for detail on the Renovate config
settings.
[dxw config]: https://github.com/dxw/renovate-config/blob/main/internal.json
[Renovate docs]: https://docs.renovatebot.com/presets-default/
> Configure renovate to auto-merge patches

- renovate.json
We used this custom config because at the time we only had one dxw Renovate config and that wasn't very client-ready. We now have a default config that is more client ready and almost exactly the same as this (though we may later move to having more options with a more conservative default), so we can just extend from that
> Use dxw Renovate config

- script/ci/cibuild
- script/ci/test
- script/docker/bootstrap
- script/docker/console
- script/docker/server
- script/docker/setup
- script/docker/test
- spec/forms/dates_form_spec.rb
Hardcoding future dates in unit tests is usually a bad idea as with the passage of time the date may move into the past and potentially break the test.
That was the case here. We now set the dates relative to 'now'.
> Remove hardcoded date of Aug 8th 2024 - that's now in the past

- app/controllers/stages/check_your_answers_stage_controller.rb
- app/controllers/submissions_controller.rb
- app/lib/submissions_reference_generator.rb
- app/models/check_your_answers/question.rb
- app/models/check_your_answers/stage.rb
- app/views/stages/check_your_answers_stage/_question_and_answer.html.erb
- app/views/stages/check_your_answers_stage/_summary_card.html.erb
- app/views/stages/check_your_answers_stage/show.erb
- app/views/submissions/successful_submission.html.erb
- config/routes.rb
- spec/controllers/submissions_controller_spec.rb
- spec/features/pilot/stage_5_check_your_answers_spec.rb
- spec/lib/submissions_reference_generator_spec.rb
In this PR we implement the final stage in the tasklist: check your answers.
The user reviews all the questions and the answers which they've given. Questions and their answers are grouped into one [Summary List](https://design-system.service.gov.uk/components/summary-list/) card per stage. The user can return to any section to edit their answers and can submit their application once they have checked their answers.
A submission [reference number](https://github.com/alphagov/govuk-design-system-backlog/issues/85) is shown in a notification [panel](https://design-system.service.gov.uk/components/panel/).
Note that at present nothing is persisted to a database. The application is saved to the user's session where it remains after submission.
In a future PR we will:
- save the application to …
> (39) Stage 5: Check your answers

- script/no-docker/setup
When running:
`script/no-docker/test`
the `shellcheck` task was picking up two cases of:
```
SC3061 (warning): In POSIX sh, read without a variable is
undefined
```
> Fix 2 shell script linting issues

- app/forms/dates_form.rb
- app/views/stages/dates_stage/show.html.erb
- spec/forms/dates_form_spec.rb
This is a first pass at a simple iteration of this feature, with a maximum permitted stay of 14 days.
> Add validation to ensure that departure date does not exceed maximum permitted stay

- Gemfile
- Gemfile.lock
- Procfile
- app/controllers/application_controller.rb
- app/controllers/pilots_controller.rb
- app/controllers/stages/check_your_answers_stage_controller.rb
- app/controllers/stages/destination_stage_controller.rb
- app/models/landable_body.rb
- config/application.rb
- db/fixtures/01_landable_bodies.rb
- db/migrate/20240820111300_create_landable_bodies.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/landable_bodies.rb
- spec/features/pilot/stage_0_start_page_understand_service_spec.rb
- spec/features/pilot/stage_1_choose_destination_spec.rb
- spec/features/pilot/stage_5_check_your_answers_spec.rb
- spec/models/landable_body_spec.rb
- spec/support/capybara.rb
In this PR we use the postgres database for the first time and introduce:
- migrations, using UUID as primary key
- the `seed-fu` gem for seeding data (run with `rake db:seed_fu`)
- the use of the `Procfile` for running `rake` tasks on each release to Heroku
- `FactoryBot` for creating db records for tests
> (8) Store "landable bodies" in db rather than hardcoded

- Gemfile
- Gemfile.lock
- app/controllers/submissions_controller.rb
- app/lib/application_reference_generator.rb
- app/lib/submissions_processor.rb
- app/models/landable_body.rb
- app/models/landing_application.rb
- app/views/submissions/successful_submission.html.erb
- db/migrate/20240821164300_create_landing_applications.rb
- db/schema.rb
- spec/controllers/submissions_controller_spec.rb
- spec/forms/dates_form_spec.rb
- spec/lib/application_reference_generator_spec.rb
- spec/lib/submissions_processor_spec.rb
- spec/rails_helper.rb
[Trello ticket](https://trello.com/c/l4dTJ6lH/45-store-submitted-application-in-db)
In this PR we:
- introduce a `SubmissionsProcessor` with responsibility for creating a `LandingApplication` from the questionnaire data stored in the session and the submission (or "application") reference
- describe the interface between the `SubmissionsController` and the `SubmissionsProcessor` with a unit test in which all other collaborating classes are mocked (`SubmissionReferenceGenerator`, `LandingApplication`, `LandableBody`). We allow our unit testing to steer us towards dependency injection (passing `LandingApplication` and `LandableBody` into the constructor of the `SubmissionsProcessor`)
- convert our naive plain Ruby `LandingApplication` to an ActiveRecord class backed by the …
> (45) Store submitted application in db

- app/controllers/submissions_controller.rb
- app/repositories/answers_repository.rb
- app/views/submissions/successful_submission.html.erb
- spec/controllers/submissions_controller_spec.rb
- spec/features/pilot/stage_5_check_your_answers_spec.rb
- spec/repositories/answers_repository_spec.rb
[Trello 45](https://trello.com/c/l4dTJ6lH/45-store-submitted-application-in-db)
Clear answers from session after submission.
This allows the user to make a fresh application.
We clear all the landing application data from the session -- that is all keys except those named:
- `session_id` and
- `_csrf_token`
> (45 pt 2) Clear answers from session on submission of application

- app/controllers/stages/dates_stage_controller.rb
- app/forms/dates_form.rb
- app/services/bank_holidays_service.rb
- config/bank_holidays_uk.json
- spec/controllers/dates_stage_controller_spec.rb
- spec/forms/dates_form_spec.rb
- spec/services/bank_holidays_service_spec.rb
Ensures the above with the addition of a bank holiday service to return BHs for England and Wales.
> Check landing departure dates do not fall on a UK bank holiday

- .github/workflows/trigger_e2e_tests.yml
- README.md
See [GitHub docs][] and [Github Action][].
We send a trigger for an action called `trigger-e2e-tests`
to our E2E repo (`dxw/dfsseta-apply-for-landing-e2e`).
This is triggered on each merge to the `main` branch.
Access to the E2E repo is authorised with a ["fine-grained
personal access token"][] (PAT)
[GitHub docs]:
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch
[Github Action]:
https://github.com/marketplace/actions/repository-dispatch
["fine-grained personal access token"]:
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token
> Trigger E2E tests using 'repository-dispatch'

- app/controllers/officer/landing_applications_controller.rb
- app/views/officer/landing_applications/index.html.erb
- config/routes.rb
- spec/controllers/landing_applications_controller_spec.rb
- spec/factories/landing_applications.rb
- spec/features/officer/view_landing_applications_spec.rb
Adds a new route, `offier/landing-applications`, for DfSSETA officers to view all landing applications, with the most recently submitted applications first.
> Officer views list of landing applications

- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
In order to guard against N+1 queries we use the Rails ["strict_loading" controls][] to alert if we lazily load records.
Individual environments specify whether to raise `StrictLoadingViolationError` when a failure to [eager load][] is detected:
- *raises* in development and test
- *logs* in production
We disable strict_loading if we're in a console session as this would otherwise be inconvenient when exploring data.
For example if we write a test assertion which attempts to lazily load an associated model we'll see an error like:
```
1) Officer views list of landing applications Officer views list of landing applications
Failure/Error: expect(page).to have_content(landing_application.destination.name)
ActiveRecord::StrictLoadingViolationError:
`LandingApplication` is marked for …
```
> (53) Apply Rails' strict_loading to all models

- Gemfile
- Gemfile.lock
- app/controllers/api/landing_applications_controller.rb
- config/initializers/rswag_api.rb
- config/initializers/rswag_ui.rb
- config/routes.rb
- config/secrets.yml
- spec/api/landing_applications_spec.rb
- spec/swagger_helper.rb
- swagger/v1/swagger.yaml
[Trello 68](https://trello.com/c/Wr5T6OLU/68-choose-openapi-tooling)
We install and configure RSwag libraries for TDD with OpenAPI.
With these libraries we'll
- write integration tests to describe our API endpoints
- generate OpenAPI specs
- expose these OpenAPI specs at `/api-docs/index.html` to
assist consumers of the API
NOTE
There's a manual step which needs to be completed after
changing the integration tests in order to update the
OpenAPI specs:
```
rake rswag:specs:swaggerize
```
This rewrites the OpenAPI spec, in YAML format at:
```
swagger/v1/swagger.yaml
```
> (68) Setup OpenAPI development harness

- .env.test
- README.md
- Rakefile
- app/controllers/api/landing_applications_controller.rb
- app/entities/landing_application_entity.rb
- config/initializers/rswag_ui.rb
- script/all/test
- spec/api/landing_applications_spec.rb
- spec/controllers/api/landing_applications_controller_spec.rb
- spec/entities/landing_application_entity_spec.rb
- swagger/v1/swagger.yaml
In this PR we:
- introduce a "presenter" class `LandingApplicationEntity` with responsibility for creating a representation of a `LandingApplication` to be exposed in JSON at the `/api/landing-applications` endpoint
- use Rswag's `example` method to set the OpenAPI spec's example response from our test fixture
- make some changes to our testing toolchain to ensure that the OpenAPI spec is updated and formatted reliably
> (69) Expose list of landing applications

- .gitignore
- Gemfile
- Gemfile.lock
In this PR we provide some support for developing with VSCode:
Add gems to aid dev with VSCode
- solargraph language server: the [solargraph gem][] works
with the [VSCode Solargraph extension][] to provide a lot of
functionality for exploring the code and language
- the [htmlbeautifier gem][] is required by VS Code's
[ERB Formatter/Beautify extension][]
[solargraph gem]:
https://github.com/castwide/solargraph
[VSCode Solargraph extension]:
https://marketplace.visualstudio.com/items?itemName=castwide.solargraph
[htmlbeautifier gem]:
https://github.com/threedaymonk/htmlbeautifier
[ERB Formatter/Beautify extension]:
https://marketplace.visualstudio.com/items?itemName=aliariff.vscode-erb-beautify
> Support development with VSCode

- README.md
- db/fixtures/development/02_landing_applications.rb
10 of each temporal category:
- *past* (landing between 2 and 11 weeks past)
- *current* (landing within the next 3 days)
- *future* (landing between 2 and 11 weeks in the future)
This seeding only runs in the local *development*
environment.
We specify `LandingApplication.seed_once` as we don't want our seeded applications to be updated (with new random dates / destination) every time the seeding process is run.
> Seed 30 landing applications in local dev environment

- .github/workflows/continuous-integration.yml
Similar to in our Rails and Nest templates, this seems to slow CI down, so it's probably quicker not to use a cache
The branch this commit is on was originally branched off renovate/node-20.x for the purpose of comparison. CI had been run on that branch multiple times, but the "Run actions/cache@v3" step couldn't find a matching cache for whatever reason. It spends almost three minutes building that cache at the end of each test CI job run. The first run of this branch was - expectedly - about three minutes quicker than the reference branch (6m13s vs 3m25s)
https://github.com/dxw/rails-template/commit/1f78864444f22c4ae4372a7a584fda1e55dba88f
https://github.com/dxw/nest-template/commit/75890e11aad58773fdd0330b2796391fba5bfac7
> Remove docker caching from CI

- docker-compose.ci.yml
- docker-compose.test.yml
This is obsolete: https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-optional
> Remove version from Docker compose files

- .env.example
- README.md
- app/controllers/api/landing_applications_controller.rb
- app/lib/api_client_authenticator.rb
- app/models/api_key.rb
- db/migrate/20240916110956_create_api_keys.rb
- db/schema.rb
- spec/api/landing_applications_spec.rb
- spec/controllers/api/landing_applications_controller_spec.rb
- spec/lib/api_client_authenticator_spec.rb
- spec/models/api_key_spec.rb
- spec/swagger_helper.rb
- swagger/v1/swagger.yaml
[Trello 70](https://trello.com/c/cd1SJ8q0/70-restrict-access-to-requests-with-api-key-provided-in-header)
Authentication is by way of an API key, passed in a header, e.g.
```sh
curl "https://apply-for-landing-ruby-4492c2b72668.herokuapp.com/api/landing-applications" \
-H 'X-API-KEY: my-secret-api-key'
```
See individual commits for details.
NB: we can now use the "Authorize" feature within the Swagger-UI
at `/api-docs/index.html` to make authorised requests.
> (70) Restrict access to requests with API key

- Gemfile
- Gemfile.lock
- app/controllers/officer/decisions_controller.rb
- app/forms/assessment_decision_form.rb
- app/models/landing_application.rb
- app/models/user.rb
- app/views/officer/decisions/new.html.erb
- app/views/officer/landing_applications/index.html.erb
- config/routes.rb
- db/fixtures/development/02_landing_applications.rb
- db/migrate/20240909125011_add_user_association_to_landing_application.rb
- db/migrate/20240913140449_add_decision_enum_to_landing_application.rb
- db/schema.rb
- spec/controllers/officer/decisions_controller_spec.rb
- spec/factories/landing_applications.rb
- spec/features/officer/assess_landing_application_spec.rb
- spec/features/officer/view_landing_applications_spec.rb
- spec/forms/assessment_decision_form_spec.rb
- spec/models/landing_application_spec.rb
- spec/models/user_spec.rb
- spec/spec_helper.rb
This is a complete new journey for our officer user, allowing them to approve or deny an application for landing. This involves changes at the data layer (associating our LandingApplication and User models), as well as an update to our application seeding to ensure applications have a decision (or no decision) assigned to them at random.
For now we don't have readable application IDs, so we are lacking a clear visual indication of the application being assessed. This will have to come in a future iteration.
> Officer records assessment decision

- .github/workflows/heroku-deployment.yml
Deployments have been failing for a while e.g. [this one](https://github.com/dxw/dfsseta-apply-for-landing-ruby/actions/runs/14313929923), as the new version of `ubuntu-latest` doesn't come with `heroku-cli` installed, as per [this issue](https://github.com/AkhileshNS/heroku-deploy/issues/188), so here we install it manually as directed in the README [here](https://github.com/AkhileshNS/heroku-deploy?tab=readme-ov-file#getting-started).
> Install Heroku CLI as part of deployment action

- db/migrate/20240913140449_add_decision_enum_to_landing_application.rb
This was failing on deployment but not on CI or locally, likely due to there being old data in Production. Here's the error we were seeing:
```
PG::DatatypeMismatch: ERROR:  column "application_decision" cannot be cast automatically to type integer
HINT:  You might need to specify "USING application_decision::integer".
```
This appears to be the way to cast types to integers that can't be done automatically according to the accepted answer in [this Stack Overflow thread](https://stackoverflow.com/questions/44131984/activerecord-column-cannot-be-cast-automatically-to-type-numeric)
Ideally we'd not edit an existing migration here, but as this is not applying on Production we don't really have much choice!
> Cast `application_decision` integers in migration
